#!/bin/bash
set -e

PGPASSWORD="$POSTGRESQL_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRESQL_USERNAME" --dbname "$POSTGRESQL_DATABASE" <<-EOSQL
  CREATE DATABASE kratos;
  GRANT ALL PRIVILEGES ON DATABASE kratos TO $POSTGRESQL_USERNAME;

  CREATE EXTENSION IF NOT EXISTS ltree;
EOSQL
