export * from './create-coach.command-handler.js'
export * from './create-person.command-handler.js'
export * from './update-coach.command-handler.js'
export * from './update-person.command-handler.js'
export * from './create-figure-skating-judge.command-handler.js'
export * from './create-figure-skating-sportsman.command-handler.js'
export * from './update-figure-skating-judge.command-handler.js'
export * from './update-figure-skating-sportsman.command-handler.js'
