version: '3.8'

services:
  yarn:
    image: node:19.9
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    volumes:
      - .config/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
    ports:
      - 5432:5432

  standalone:
    image: node:19.9
    working_dir: /workspace
    volumes:
      - ./:/workspace:z
    entrypoint: yarn workspace @standalone/service-entrypoint dev
    environment:
      - DB_HOST=db
    ports:
      - 3000:3000

  app:
    image: node:19.9
    working_dir: /workspace
    volumes:
      - ./:/workspace:z
    entrypoint: yarn workspace @app/renderer-entrypoint dev
    environment:
      - GATEWAY_URL=http://standalone:3000
    ports:
      - 3001:3000
