export * from './person-created.event.js'
export * from './person-updated.event.js'
export * from './coach-created.event.js'
export * from './coach-updated.event.js'
export * from './figure-skating-sportsman-created.event.js'
export * from './figure-skating-sportsman-updated.event.js'
export * from './figure-skating-judge-created.event.js'
export * from './figure-skating-judge-updated.event.js'
