export enum OrganizationState {
  CREATED = 0,
  WAIT_REVISE = 1,
  CANCELED = 2,
  DENIED = 3,
  IN_REGISTRY = 4,
  NOT_IN_REGISTRY = 5,
  DOES_NOT_EXIST = 6,
  ACTUALIZATION = 7,
  ACTUALIZATION_FAILED = 8,
  ACTUALIZATION_CHECK = 9,
}
