export enum SportsmanRank {
  NOT_SPECIFIED = 0,
  NO_RANK = 1,
  THIRD_YOUTH = 2,
  SECOND_YOUTH = 3,
  FIRST_YOUTH = 4,
  THIRD_SPORTS = 5,
  SECOND_SPORTS = 6,
  FIRST_SPORTS = 7,
  CANDIDATE_MASTER_OF_SPORTS = 8,
  MASTER_OF_SPORTS = 9,
  INTERNATIONAL_MASTER_OF_SPORTS = 10,
  HONORED_MASTER_OF_SPORTS = 11,
}
