export * from './create-person.command.js'
export * from './create-coach.command.js'
export * from './update-coach.command.js'
export * from './update-person.command.js'
export * from './create-figure-skating-sportsman.command.js'
export * from './create-figure-skating-judge.command.js'
export * from './update-figure-skating-sportsman.command.js'
export * from './update-figure-skating-judge.command.js'
