export * from './create-person.serializer.js'
export * from './update-person.serializer.js'
export * from './create-coach.serializer.js'
export * from './update-coach.serializer.js'
export * from './create-figure-skating-sportsman.serializer.js'
export * from './update-figure-skating-sportsman.serializer.js'
export * from './create-figure-skating-judge.serializer.js'
export * from './update-figure-skating-judge.serializer.js'
