export * from './create-person.payload.js'
export * from './update-person.payload.js'
export * from './create-coach.payload.js'
export * from './update-coach.payload.js'
export * from './create-figure-skating-sportsman.payload.js'
export * from './update-figure-skating-sportsman.payload.js'
export * from './create-figure-skating-judge.payload.js'
export * from './update-figure-skating-judge.payload.js'
